<!-- jQuery JS -->
<script src="{{ asset('shop/js/vendor/jquery-1.12.4.min.js') }}"></script>
<!-- Popper JS -->
<script src="{{ asset('shop/js/popper.min.js') }}"></script>
<!-- Bootstrap JS -->
<script src="{{ asset('shop/js/bootstrap.min.js') }}"></script>
<!-- Plugins JS -->
<script src="{{ asset('shop/js/plugins.js') }}"></script>
<!-- Main JS -->
<script src="{{ asset('shop/js/main.js') }}"></script>
